### ISSUE TITLE
Error thrown when attempting to make rnsmr.json url

### ISSUE THREAD

**Issue by interianow** [rhdeck/react-native-swift-registry#1]
RNSMainRegistry.swift module throws error when calling `getFileUrl`
> Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Foundation._GenericObjCError.nilError

Project is running on Xcode 10

Workaround I am using at the moment is:
1. Have `loadData` return [:]
2. Have `saveDataFile` return true

**Comment by rhdeck** [comment]
Fixed in trunk
